language: android
android:
 components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

jdk: oraclejdk8

before_install:
- yes | sdkmanager "platforms;android-27"

script: ./gradlew testDebug
