language: android
android:
 components:
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository

jdk: oraclejdk8

script: echo "1"

after_success:
   - python sputnik-ci.py
