language: android
android:
 components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

jdk: oraclejdk8

script: ./gradlew testDebug

after_success:
    - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
