name: Android CI
on: [pull_request]

jobs:
  Build-UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew assembleDebug testDebugUnitTest
      - name: Android monkeyrunner
        uses: ReactiveCircus/android-emulator-runner@v2.8.0
        with:
          api-level: 28
          disable-animations: true
          script: ./gradlew installDebug && adb shell monkey -p com.fsck.k9 -v 200
  ktlintCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew ktlintCheck
  Espresso:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Android monkeyrunner
        uses: ReactiveCircus/android-emulator-runner@v2.8.0
        with:
          api-level: 28
          disable-animations: true
          script: adb shell monkey -p com.fsck.k9 -v 200
