name: Android CI
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 8.0.252
    - name: Build with Gradle
      run: ./gradlew -i :mail:protocols:imap:testDebugUnitTest
